### ISSUE TITLE
unable to create nested array

### ISSUE THREAD

**Issue by horijon** [BeameryHQ/json-ditto#15]
Want to convert/unflatten from
```
const jsonData = {
    "description": "SARS-CoV-2 (COVID-19) IgM Ab [Units/volume] in Serum or Plasma by Immunoassay"
};
```
to result
```
{
   "category":[
      {
         "coding":[
            {
               "display":"SARS-CoV-2 (COVID-19) IgM Ab [Units/volume] in Serum or Plasma by Immunoassay"
            }
         ]
      }
   ]
}
```

How do i write mapping logic for such case? 
@ahmadassaf I am eagerly seeking for your kind help! And thank you for the library!

**Comment by ahmadassaf** [comment]
Hi @horijon,

to achieve the above you can define your mappings as:

```
{
  category: [{
    coding: {
      "output": [],
      "innerDocument": "!",
      "mappings": {
          "value": "description"
      }
    }
  }]
}
```
I created a sample repl.it example for you [here](https://replit.com/@ahmadassaf1/Ditto#index.js) and you can see that the output will be:

```
{
  "category": {
    "coding": [
      {
        "value": "SARS-CoV-2 (COVID-19) IgM Ab [Units/volume] in Serum or Plasma by Immunoassay"
      }
    ]
  }
}
```

**Comment by ahmadassaf** [comment]
if you will always have the same exact structure, so only one item in the array it is as simple as a JSON path traversal.

```
{
  description: "category[0].coding[0].value"
}
```
