### ISSUE TITLE
Implement switch case scenario

### ISSUE THREAD

**Issue by sarojpurbey324** [BeameryHQ/json-ditto#17]
Hello @ahmadassaf,
I need to implement switch case scenario.

I have following set of input json data with corresponding expected json output.
1st sample of input data:
{
status:'requested'
}

expected output:
{
status:'proposed'
}

2nd sample of input data
{
status:'pending'
}

expected output:
{
status:'scheduled'
}

3rd sample of input data
{
status:'completed'
}

expected output:
{
status:'fulfilled'
}

Please help implement it.

**Comment by ahmadassaf** [comment]
Please open issues that are relevant to bugs in the code and not problems you have in creating mappings! The documentation and samples are clear enough
